export interface NavigationRoutesInterface {
    route: string
}

export const navigationRoutes: NavigationRoutesInterface[] = [
    { route: '/canva' },
    { route: '/multiagente' },
    // Panel (admin section)
    { route: '/panel' },
    { route: '/panel/module' },
    { route: '/panel/conexion' },
    { route: '/panel/clientes' },
    { route: '/panel/reseller' },
    { route: '/panel/templates' },
    { route: '/panel/client-billing' },
    { route: '/panel/external-data' },
    { route: '/panel/password' },
    { route: '/panel/register-links' },
    { route: '/panel/credits' },
    // Legacy admin routes (kept for backward compat)
    { route: '/admin/module' },
    { route: '/admin/conexion' },
    { route: '/admin/clientes' },
    { route: '/admin/reseller' },
    { route: "/admin/templates" },
    { route: "/admin/client-billing" },
    { route: "/admin/external-data" },
    { route: "/admin" },
    { route: "/documentation" },
    { route: "/dashboard" },
    { route: "/connection" },
    { route: "/crm" },
    { route: "/crm/dashboard" },
    { route: "/crm/rules" },
    { route: "/ia" },
    { route: "/tags" },
    { route: "/ai" },
    { route: "/ai-image" },
    { route: "/products" },
    { route: "/chats" },
    { route: "/sessions" },
    { route: "/flow" },
    { route: "/workflow" },
    { route: "/campaigns" },
    { route: "/tools" },
    { route: "/reminders" },
    { route: "/auto-replies" },
    { route: "/profile" },
    { route: "/templates" },
    { route: "/evo" },
    { route: "/evo?slot=1" },
    { route: "/evo?slot=2" },
    { route: "/evo?slot=3" },
    { route: "/evo?slot=4" },
    { route: "/evo?slot=5" },
    { route: "/panel/evo" },
    //TOOLS
    { route: "/tools/tool-1" },
    { route: "/tools/tool-2" },
    { route: "/tools/tool-3" },
    { route: "/tools/tool-4" },
    { route: "/tools/tool-5" },
    // { route: "/with-out-route" },
    { route: "/schedule" },
    { route: "/my-data" },
];
