export interface NavigationRoutesInterface {
    route: string
}

export const navigationRoutes: NavigationRoutesInterface[] = [
    { route: '/canva' },
    { route: '/multiagente' },
    { route: '/equipo' },
    // Panel (admin section)
    { route: '/panel' },
    { route: '/panel/module' },
    { route: '/panel/conexion' },
    { route: '/panel/clientes' },
    { route: '/panel/reseller' },
    { route: '/panel/templates' },
    { route: '/panel/client-billing' },
    { route: '/panel/external-data' },
    { route: '/panel/password' },
    { route: '/panel/register-links' },
    { route: '/panel/credits' },
    { route: '/panel/afiliados' },
    { route: "/documentation" },
    { route: "/dashboard" },
    { route: "/connection" },
    { route: "/crm" },
    { route: "/crm/dashboard" },
    { route: "/crm/rules" },
    { route: "/crm/kanban" },
    { route: "/ia" },
    { route: "/tags" },
    { route: "/tareas" },
    { route: "/ai" },
    { route: "/ai-image" },
    { route: "/products" },
    { route: "/chats" },
    { route: "/sessions" },
    { route: "/flow" },
    { route: "/workflow" },
    { route: "/campaigns" },
    { route: "/tools" },
    { route: "/reminders" },
    { route: "/auto-replies" },
    { route: "/profile" },
    { route: "/templates" },
    { route: "/evo" },
    { route: "/evo?slot=1" },
    { route: "/evo?slot=2" },
    { route: "/evo?slot=3" },
    { route: "/evo?slot=4" },
    { route: "/evo?slot=5" },
    { route: "/panel/evo" },
    //TOOLS
    { route: "/tools/tool-1" },
    { route: "/tools/tool-2" },
    { route: "/tools/tool-3" },
    { route: "/tools/tool-4" },
    { route: "/tools/tool-5" },
    // { route: "/with-out-route" },
    { route: "/schedule" },
    { route: "/bookings" },
    { route: "/my-data" },
    { route: "/notas" },
    { route: "/afiliados" },
    { route: "/clientes" },
    { route: "/cotizaciones" },
    { route: "/credits" },
    { route: "/messages" },
    { route: "/planes" },
    { route: "/qr" },
    { route: "/tools/docs" },
    { route: "/tools/drive" },
    { route: "/tools/sheets" },
    { route: "/dashboard/finance" },
    { route: "/dashboard/finance/accounts" },
    { route: "/dashboard/finance/expenses" },
    { route: "/dashboard/finance/sales" },
    { route: "/dashboard/finance/settings" },
    { route: "/documentation/guide" },
    { route: "/documentation/tutorial" },
    // Panel (admin section) - adicionales
    { route: "/panel/pagos" },
    { route: "/panel/planes" },
    { route: "/panel/suscripciones" },
    { route: "/panel/tools" },
];
