'use server'

export interface Country {
    name: string
    code: string
    flag: string
}

const FALLBACK_COUNTRIES = [
  { name: 'Afghanistan',               codes: ['+93'],              flag: 'https://flagcdn.com/af.svg' },
  { name: 'Albania',                   codes: ['+355'],             flag: 'https://flagcdn.com/al.svg' },
  { name: 'Algeria',                   codes: ['+213'],             flag: 'https://flagcdn.com/dz.svg' },
  { name: 'Argentina',                 codes: ['+54'],              flag: 'https://flagcdn.com/ar.svg' },
  { name: 'Armenia',                   codes: ['+374'],             flag: 'https://flagcdn.com/am.svg' },
  { name: 'Australia',                 codes: ['+61'],              flag: 'https://flagcdn.com/au.svg' },
  { name: 'Austria',                   codes: ['+43'],              flag: 'https://flagcdn.com/at.svg' },
  { name: 'Azerbaijan',                codes: ['+994'],             flag: 'https://flagcdn.com/az.svg' },
  { name: 'Bahrain',                   codes: ['+973'],             flag: 'https://flagcdn.com/bh.svg' },
  { name: 'Bangladesh',                codes: ['+880'],             flag: 'https://flagcdn.com/bd.svg' },
  { name: 'Belarus',                   codes: ['+375'],             flag: 'https://flagcdn.com/by.svg' },
  { name: 'Belgium',                   codes: ['+32'],              flag: 'https://flagcdn.com/be.svg' },
  { name: 'Bolivia',                   codes: ['+591'],             flag: 'https://flagcdn.com/bo.svg' },
  { name: 'Bosnia and Herzegovina',    codes: ['+387'],             flag: 'https://flagcdn.com/ba.svg' },
  { name: 'Brazil',                    codes: ['+55'],              flag: 'https://flagcdn.com/br.svg' },
  { name: 'Bulgaria',                  codes: ['+359'],             flag: 'https://flagcdn.com/bg.svg' },
  { name: 'Cambodia',                  codes: ['+855'],             flag: 'https://flagcdn.com/kh.svg' },
  { name: 'Cameroon',                  codes: ['+237'],             flag: 'https://flagcdn.com/cm.svg' },
  { name: 'Canada',                    codes: ['+1'],               flag: 'https://flagcdn.com/ca.svg' },
  { name: 'Chile',                     codes: ['+56'],              flag: 'https://flagcdn.com/cl.svg' },
  { name: 'China',                     codes: ['+86'],              flag: 'https://flagcdn.com/cn.svg' },
  { name: 'Colombia',                  codes: ['+57'],              flag: 'https://flagcdn.com/co.svg' },
  { name: 'Congo',                     codes: ['+243'],             flag: 'https://flagcdn.com/cd.svg' },
  { name: 'Costa Rica',                codes: ['+506'],             flag: 'https://flagcdn.com/cr.svg' },
  { name: 'Croatia',                   codes: ['+385'],             flag: 'https://flagcdn.com/hr.svg' },
  { name: 'Cuba',                      codes: ['+53'],              flag: 'https://flagcdn.com/cu.svg' },
  { name: 'Czech Republic',            codes: ['+420'],             flag: 'https://flagcdn.com/cz.svg' },
  { name: 'Denmark',                   codes: ['+45'],              flag: 'https://flagcdn.com/dk.svg' },
  { name: 'Dominican Republic',        codes: ['+1809','+1829','+1849'], flag: 'https://flagcdn.com/do.svg' },
  { name: 'Ecuador',                   codes: ['+593'],             flag: 'https://flagcdn.com/ec.svg' },
  { name: 'Egypt',                     codes: ['+20'],              flag: 'https://flagcdn.com/eg.svg' },
  { name: 'El Salvador',               codes: ['+503'],             flag: 'https://flagcdn.com/sv.svg' },
  { name: 'Ethiopia',                  codes: ['+251'],             flag: 'https://flagcdn.com/et.svg' },
  { name: 'Finland',                   codes: ['+358'],             flag: 'https://flagcdn.com/fi.svg' },
  { name: 'France',                    codes: ['+33'],              flag: 'https://flagcdn.com/fr.svg' },
  { name: 'Georgia',                   codes: ['+995'],             flag: 'https://flagcdn.com/ge.svg' },
  { name: 'Germany',                   codes: ['+49'],              flag: 'https://flagcdn.com/de.svg' },
  { name: 'Ghana',                     codes: ['+233'],             flag: 'https://flagcdn.com/gh.svg' },
  { name: 'Greece',                    codes: ['+30'],              flag: 'https://flagcdn.com/gr.svg' },
  { name: 'Guatemala',                 codes: ['+502'],             flag: 'https://flagcdn.com/gt.svg' },
  { name: 'Haiti',                     codes: ['+509'],             flag: 'https://flagcdn.com/ht.svg' },
  { name: 'Honduras',                  codes: ['+504'],             flag: 'https://flagcdn.com/hn.svg' },
  { name: 'Hungary',                   codes: ['+36'],              flag: 'https://flagcdn.com/hu.svg' },
  { name: 'India',                     codes: ['+91'],              flag: 'https://flagcdn.com/in.svg' },
  { name: 'Indonesia',                 codes: ['+62'],              flag: 'https://flagcdn.com/id.svg' },
  { name: 'Iran',                      codes: ['+98'],              flag: 'https://flagcdn.com/ir.svg' },
  { name: 'Iraq',                      codes: ['+964'],             flag: 'https://flagcdn.com/iq.svg' },
  { name: 'Ireland',                   codes: ['+353'],             flag: 'https://flagcdn.com/ie.svg' },
  { name: 'Israel',                    codes: ['+972'],             flag: 'https://flagcdn.com/il.svg' },
  { name: 'Italy',                     codes: ['+39'],              flag: 'https://flagcdn.com/it.svg' },
  { name: 'Jamaica',                   codes: ['+1876'],            flag: 'https://flagcdn.com/jm.svg' },
  { name: 'Japan',                     codes: ['+81'],              flag: 'https://flagcdn.com/jp.svg' },
  { name: 'Jordan',                    codes: ['+962'],             flag: 'https://flagcdn.com/jo.svg' },
  { name: 'Kazakhstan',                codes: ['+7'],               flag: 'https://flagcdn.com/kz.svg' },
  { name: 'Kenya',                     codes: ['+254'],             flag: 'https://flagcdn.com/ke.svg' },
  { name: 'Kuwait',                    codes: ['+965'],             flag: 'https://flagcdn.com/kw.svg' },
  { name: 'Lebanon',                   codes: ['+961'],             flag: 'https://flagcdn.com/lb.svg' },
  { name: 'Libya',                     codes: ['+218'],             flag: 'https://flagcdn.com/ly.svg' },
  { name: 'Malaysia',                  codes: ['+60'],              flag: 'https://flagcdn.com/my.svg' },
  { name: 'Mexico',                    codes: ['+52'],              flag: 'https://flagcdn.com/mx.svg' },
  { name: 'Morocco',                   codes: ['+212'],             flag: 'https://flagcdn.com/ma.svg' },
  { name: 'Mozambique',                codes: ['+258'],             flag: 'https://flagcdn.com/mz.svg' },
  { name: 'Myanmar',                   codes: ['+95'],              flag: 'https://flagcdn.com/mm.svg' },
  { name: 'Nepal',                     codes: ['+977'],             flag: 'https://flagcdn.com/np.svg' },
  { name: 'Netherlands',               codes: ['+31'],              flag: 'https://flagcdn.com/nl.svg' },
  { name: 'New Zealand',               codes: ['+64'],              flag: 'https://flagcdn.com/nz.svg' },
  { name: 'Nicaragua',                 codes: ['+505'],             flag: 'https://flagcdn.com/ni.svg' },
  { name: 'Nigeria',                   codes: ['+234'],             flag: 'https://flagcdn.com/ng.svg' },
  { name: 'Norway',                    codes: ['+47'],              flag: 'https://flagcdn.com/no.svg' },
  { name: 'Oman',                      codes: ['+968'],             flag: 'https://flagcdn.com/om.svg' },
  { name: 'Pakistan',                  codes: ['+92'],              flag: 'https://flagcdn.com/pk.svg' },
  { name: 'Panama',                    codes: ['+507'],             flag: 'https://flagcdn.com/pa.svg' },
  { name: 'Paraguay',                  codes: ['+595'],             flag: 'https://flagcdn.com/py.svg' },
  { name: 'Peru',                      codes: ['+51'],              flag: 'https://flagcdn.com/pe.svg' },
  { name: 'Philippines',               codes: ['+63'],              flag: 'https://flagcdn.com/ph.svg' },
  { name: 'Poland',                    codes: ['+48'],              flag: 'https://flagcdn.com/pl.svg' },
  { name: 'Portugal',                  codes: ['+351'],             flag: 'https://flagcdn.com/pt.svg' },
  { name: 'Puerto Rico',               codes: ['+1787','+1939'],    flag: 'https://flagcdn.com/pr.svg' },
  { name: 'Qatar',                     codes: ['+974'],             flag: 'https://flagcdn.com/qa.svg' },
  { name: 'Romania',                   codes: ['+40'],              flag: 'https://flagcdn.com/ro.svg' },
  { name: 'Russia',                    codes: ['+7'],               flag: 'https://flagcdn.com/ru.svg' },
  { name: 'Saudi Arabia',              codes: ['+966'],             flag: 'https://flagcdn.com/sa.svg' },
  { name: 'Senegal',                   codes: ['+221'],             flag: 'https://flagcdn.com/sn.svg' },
  { name: 'Serbia',                    codes: ['+381'],             flag: 'https://flagcdn.com/rs.svg' },
  { name: 'Singapore',                 codes: ['+65'],              flag: 'https://flagcdn.com/sg.svg' },
  { name: 'Slovakia',                  codes: ['+421'],             flag: 'https://flagcdn.com/sk.svg' },
  { name: 'South Africa',              codes: ['+27'],              flag: 'https://flagcdn.com/za.svg' },
  { name: 'South Korea',               codes: ['+82'],              flag: 'https://flagcdn.com/kr.svg' },
  { name: 'Spain',                     codes: ['+34'],              flag: 'https://flagcdn.com/es.svg' },
  { name: 'Sri Lanka',                 codes: ['+94'],              flag: 'https://flagcdn.com/lk.svg' },
  { name: 'Sudan',                     codes: ['+249'],             flag: 'https://flagcdn.com/sd.svg' },
  { name: 'Sweden',                    codes: ['+46'],              flag: 'https://flagcdn.com/se.svg' },
  { name: 'Switzerland',               codes: ['+41'],              flag: 'https://flagcdn.com/ch.svg' },
  { name: 'Syria',                     codes: ['+963'],             flag: 'https://flagcdn.com/sy.svg' },
  { name: 'Taiwan',                    codes: ['+886'],             flag: 'https://flagcdn.com/tw.svg' },
  { name: 'Tanzania',                  codes: ['+255'],             flag: 'https://flagcdn.com/tz.svg' },
  { name: 'Thailand',                  codes: ['+66'],              flag: 'https://flagcdn.com/th.svg' },
  { name: 'Tunisia',                   codes: ['+216'],             flag: 'https://flagcdn.com/tn.svg' },
  { name: 'Turkey',                    codes: ['+90'],              flag: 'https://flagcdn.com/tr.svg' },
  { name: 'Uganda',                    codes: ['+256'],             flag: 'https://flagcdn.com/ug.svg' },
  { name: 'Ukraine',                   codes: ['+380'],             flag: 'https://flagcdn.com/ua.svg' },
  { name: 'United Arab Emirates',      codes: ['+971'],             flag: 'https://flagcdn.com/ae.svg' },
  { name: 'United Kingdom',            codes: ['+44'],              flag: 'https://flagcdn.com/gb.svg' },
  { name: 'United States',             codes: ['+1'],               flag: 'https://flagcdn.com/us.svg' },
  { name: 'Uruguay',                   codes: ['+598'],             flag: 'https://flagcdn.com/uy.svg' },
  { name: 'Uzbekistan',                codes: ['+998'],             flag: 'https://flagcdn.com/uz.svg' },
  { name: 'Venezuela',                 codes: ['+58'],              flag: 'https://flagcdn.com/ve.svg' },
  { name: 'Vietnam',                   codes: ['+84'],              flag: 'https://flagcdn.com/vn.svg' },
  { name: 'Yemen',                     codes: ['+967'],             flag: 'https://flagcdn.com/ye.svg' },
  { name: 'Zimbabwe',                  codes: ['+263'],             flag: 'https://flagcdn.com/zw.svg' },
].sort((a, b) => a.name.localeCompare(b.name));

export const getCountryCodes = async () => FALLBACK_COUNTRIES;
